sudo: no
language: java
jdk:
  - oraclejdk8

# whitelist
branches:
  only:
    - master
    - development

before_install:
  - mvn clean

script:
  - mvn verify

deploy:
  provider: bintray
  file: ".descriptor.json"
  user: "vauvenal5"
  key:
    secure: E9QEElm6eaLzDPIOdOm07T9DRT6bG+ZcBW7E5Rm84qiO27z5yxVXR2mDsJavOe1ZfZwM7Dgms+05XVxbgqbj2Zs+E2NyXjhuLITx0DgN3vJ/5LQsiOf+I/NB+Z5mR1i2hjta7WpxjIRS4Xi5N+mrieziTw9dnszYA1oLrzTeCJA=